spring:
# 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=CTT&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update #none
    show-sql: true
#  mvc:
#    static-path-pattern: /static/**
  #热部署生效
  devtools:
    restart:
      enabled: true


# 日志配置
logging:
  level:
    root: info
    com.ponking: debug
  file: log/blog.log
